import { QuartzComponent, QuartzComponentConstructor } from "./types"
import manifest from "./data/conceptMill.json"
// @ts-ignore
import script from "./scripts/aetheriaConceptMill.inline"
import style from "./styles/aetheriaConceptMill.scss"

// The Concept Mill: a fullscreen viewer for ship concept renders. The page
// layout is stripped for this slug (see quartz.layout.ts) so only the floating
// masthead survives. The manifest is generated by scripts/concept-mill/build.mjs
// and embedded here; the inline script renders the stage, menu and readout.
export const conceptMillSlug = "Game-Design/Concept-Mill"
export const isConceptMillPage = (slug: string | undefined) => slug === conceptMillSlug

export default (() => {
  const AetheriaConceptMill: QuartzComponent = () => {
    // Server render shows the first ship so the stage is never empty before
    // the script runs; the script then honours the URL hash.
    const first = manifest.ships[0]
    const firstVariant = first.variants.find((v) => v.id === first.defaultVariant) ?? first.variants[0]
    return (
      <div class="cm" data-concept-mill>
        <script type="application/json" class="cm-data" dangerouslySetInnerHTML={{ __html: JSON.stringify(manifest).replace(/</g, String.fromCharCode(92) + "u003c") }} />
        <div class="cm-field" aria-hidden="true" />
        <figure class="cm-stage">
          <img class="cm-render is-live" src={firstVariant.image} alt={`Concept render of the ${first.name}`} />
          <div class="cm-sweep" aria-hidden="true" />
        </figure>
        <noscript>
          <p class="cm-noscript">The Concept Mill needs JavaScript. The renders and their prompt records are in /media/concept-mill/.</p>
        </noscript>
      </div>
    )
  }

  AetheriaConceptMill.css = style
  AetheriaConceptMill.afterDOMLoaded = script
  return AetheriaConceptMill
}) satisfies QuartzComponentConstructor
